language: java

sudo: required

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10

env:
  - TARGET_DIST=ubuntu TARGET_VER=1804
  - TARGET_DIST=ubuntu TARGET_VER=1604
  - TARGET_DIST=debian TARGET_VER=8

script:
  - bash buildRTC.sh
  
