dist: xenial
language: java

before_install:
  - sudo apt-get install junit
  - sudo apt-get install ant-optional

addons:
  apt:
    packages:
    - ant

jdk:
#  - oraclejdk8
  - openjdk8

script:
  - bash buildRTC.sh
  - ./jp.go.aist.rtm.RTC/src/RTMExamples_scripts/start-orbd.sh &
  - bash buildTests.sh
