dist: xenial
language: java

addons:
  apt:
    packages:
    - ant

jdk:
#  - oraclejdk8
  - openjdk8

script:
  - bash buildRTC.sh
#  - ./jp.go.aist.rtm.RTC/src/RTMExamples_scripts/start-orbd.sh
#  - bash buildTests.sh
